// Renders the committed email templates with sample values and screenshots them, light and dark:
//   pnpm email:preview                 every template, into .email-preview/ (gitignored)
//   pnpm email:preview magic_link      one template
//
// What it shows is the file Supabase sends (supabase/templates/*.html, generated by design/emails.mjs),
// with each Go-template variable replaced by the sample its email file names. Dark is Chromium's
// `prefers-color-scheme: dark`, i.e. the <style> block's rules, the way Apple Mail or iOS Mail apply
// them. It cannot show Gmail's or Outlook's own rendering (docs/DEVELOPMENT.md, "Emails").
// Each template gets a phone-width and a desktop-width shot per scheme, plus the rendered .html.
import { mkdirSync, writeFileSync, readFileSync, readdirSync } from 'node:fs'
import { basename } from 'node:path'
import { pathToFileURL } from 'node:url'
import { chromium } from '@playwright/test'

const repo = new URL('../../', import.meta.url)
const out = new URL('../.email-preview/', import.meta.url)
mkdirSync(out, { recursive: true })

// The samples live next to the template's source, so a new email names its own variables.
const only = process.argv[2]
const names = readdirSync(new URL('design/emails/', repo))
  .filter((file) => file.endsWith('.mjs') && !['shell.mjs', 'color.mjs'].includes(file))
  .map((file) => basename(file, '.mjs'))
  .filter((name) => !only || name === only)
if (!names.length) throw new Error(`No email "${only}" in design/emails/.`)

const VIEWPORTS = { phone: { width: 390, height: 640 }, desktop: { width: 760, height: 640 } }

const browser = await chromium.launch()
try {
  for (const name of names) {
    const email = await import(pathToFileURL(new URL(`design/emails/${name}.mjs`, repo).pathname).href)
    let html = readFileSync(new URL(email.output, repo), 'utf8')
    for (const [variable, value] of Object.entries(email.sample ?? {})) html = html.replaceAll(variable, value)
    const leftover = html.match(/\{\{[^}]*\}\}/g)
    if (leftover) throw new Error(`${name}: no sample for ${[...new Set(leftover)].join(', ')}`)
    writeFileSync(new URL(`${name}.html`, out), html)

    for (const [size, viewport] of Object.entries(VIEWPORTS)) {
      for (const colorScheme of ['light', 'dark']) {
        const context = await browser.newContext({ viewport, colorScheme, deviceScaleFactor: 2 })
        const page = await context.newPage()
        await page.setContent(html)
        const file = `${name}-${size}-${colorScheme}.png`
        await page.screenshot({ path: new URL(file, out).pathname, fullPage: true })
        console.log(`✓ .email-preview/${file}`)
        await context.close()
      }
    }
  }
} finally {
  await browser.close()
}
