// Generates platform token files from tokens.json.
// Web (Tailwind v4 theme) and iOS (SwiftUI); Android (Compose) gets its own format if it is built.
// Run: pnpm tokens         (from design/) rewrites the generated files
//      pnpm tokens:check   fails when the committed files differ from tokens.json
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import StyleDictionary from 'style-dictionary'

const header = '// Generated by design/build.mjs from design/tokens.json. Do not edit.\n'

const swiftColor = (hex) => {
  const n = parseInt(hex.slice(1), 16)
  const c = (v) => (v / 255).toFixed(4)
  return `SwiftUI.Color(red: ${c((n >> 16) & 255)}, green: ${c((n >> 8) & 255)}, blue: ${c(n & 255)})`
}

// A fontFamily token is the whole stack, most wanted first. CSS gets the stack
// with the real family quoted; a platform that bundles the file only wants its
// name, so Swift takes the first entry.
const stack = (value) => (Array.isArray(value) ? value : [value])
const cssFontStack = (value) => stack(value).map((f, i) => (i === 0 ? `'${f}'` : f)).join(', ')

StyleDictionary.registerFormat({
  name: 'swiftui/tokens',
  format: ({ dictionary }) => {
    const groups = new Map()
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path
      const name = rest.join('_')
      const value =
        token.$type === 'color'
          ? swiftColor(token.$value)
          : token.$type === 'fontFamily'
            ? `"${stack(token.$value)[0]}"`
            : `CGFloat(${token.$value})`
      if (!groups.has(group)) groups.set(group, [])
      groups.get(group).push(`        static let ${name} = ${value}`)
    }
    const enumName = (g) => g[0].toUpperCase() + g.slice(1)
    const body = [...groups]
      .map(([g, lines]) => `    enum ${enumName(g)} {\n${lines.join('\n')}\n    }`)
      .join('\n\n')
    return `${header}\nimport SwiftUI\n\nenum Tokens {\n${body}\n}\n`
  },
})

// Tailwind v4 theme: token groups map onto Tailwind's namespaces, so `bg-surface`,
// `px-md`, `rounded-pill`, `text-caption` (with its line height) just work.
// Durations, springs and sizes have no Tailwind namespace and stay plain variables.
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const themeNamespace = {
  color: 'color',
  space: 'spacing',
  radius: 'radius',
  fontFamily: 'font',
  fontSize: 'text',
  letterSpacing: 'tracking',
}

StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format: ({ dictionary }) => {
    const theme = []
    const root = []
    const lineHeights = new Map(
      dictionary.allTokens.filter((t) => t.path[0] === 'lineHeight').map((t) => [t.path[1], t.$value]),
    )
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path
      const name = kebab(rest.join('-'))
      const ns = themeNamespace[group]
      if (group === 'lineHeight') continue
      if (ns === 'color') theme.push(`  --color-${name}: ${token.$value};`)
      else if (ns === 'font') theme.push(`  --font-${name}: ${cssFontStack(token.$value)};`)
      // Type in rem so it follows the browser's font-size setting; the rest in px.
      else if (ns === 'text') theme.push(`  --text-${name}: ${token.$value / 16}rem;`)
      else if (ns) theme.push(`  --${ns}-${name}: ${token.$value}px;`)
      else if (group === 'duration') root.push(`  --duration-${name}: ${token.$value}ms;`)
      // Stroke widths are read back as a length (`border-(length:--stroke-hairline)`).
      else root.push(`  --${kebab(group)}-${name}: ${token.$value}${group === 'size' || group === 'stroke' ? 'px' : ''};`)
      if (group === 'fontSize' && lineHeights.has(rest[0])) {
        theme.push(`  --text-${name}--line-height: ${lineHeights.get(rest[0]) / 16}rem;`)
      }
    }
    return `/* Generated by design/build.mjs from design/tokens.json. Do not edit. */\n\n@theme {\n${theme.join('\n')}\n}\n\n:root {\n${root.join('\n')}\n}\n`
  },
})

// Where the generated files live in the repo. There is no native app yet, so the
// Swift file waits in design/generated/ until one points its build at it.
const outputs = {
  ios: { dir: 'generated/', file: 'Tokens.generated.swift', format: 'swiftui/tokens', transforms: ['name/camel'] },
  web: { dir: '../web/app/assets/css/', file: 'tokens.generated.css', format: 'css/tailwind-theme', transforms: ['name/kebab'] },
}

const here = (path) => fileURLToPath(new URL(path, import.meta.url))
const check = process.argv.includes('--check')
// A check builds into a scratch directory and compares, so it never touches the
// working tree and works the same locally and in CI.
const scratch = check ? mkdtempSync(join(tmpdir(), 'libellus-tokens-')) : null

const sd = new StyleDictionary({
  source: [here('tokens.json')],
  usesDtcg: true,
  log: { verbosity: check ? 'silent' : 'default' },
  platforms: Object.fromEntries(
    Object.entries(outputs).map(([platform, o]) => [
      platform,
      {
        transforms: o.transforms,
        buildPath: check ? `${scratch}/${platform}/` : `${here(o.dir)}/`,
        files: [{ destination: o.file, format: o.format }],
      },
    ]),
  ),
})

await sd.buildAllPlatforms()

if (check) {
  const stale = Object.entries(outputs).filter(([platform, o]) => {
    const fresh = readFileSync(join(scratch, platform, o.file), 'utf8')
    let committed = ''
    try {
      committed = readFileSync(here(o.dir + o.file), 'utf8')
    } catch {}
    return fresh !== committed
  })
  rmSync(scratch, { recursive: true, force: true })
  if (stale.length) {
    for (const [, o] of stale) {
      console.error(`✗ ${relative(here('..'), here(o.dir + o.file))} does not match tokens.json`)
    }
    console.error('Generated token files are never edited by hand. Run `pnpm tokens` in design/ and commit the result.')
    process.exit(1)
  }
  console.log('✓ generated token files match tokens.json')
}
