// Generates platform token files from tokens.json.
// Web (Tailwind v4 theme with a light and a dark theme) and iOS (SwiftUI, with
// light/dark variants); Android (Compose) gets its own format if it is built.
// Run: pnpm tokens         (from design/) rewrites the generated files
//      pnpm tokens:check   fails when the committed files differ from tokens.json
//
// A token that differs between the themes has `{ "light": …, "dark": … }` as its
// value; every other token is the same in both. Light is the default theme.
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import StyleDictionary from 'style-dictionary'

const isThemed = (value) =>
  value !== null && typeof value === 'object' && !Array.isArray(value) && 'light' in value && 'dark' in value
/** A token's value in one theme. */
const valueIn = (token, theme) => (isThemed(token.$value) ? token.$value[theme] : token.$value)

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('')
// Numbers keep a short, stable form in the output: 0.9375, not 0.93750000001.
const num = (n, digits = 4) => String(Number(n.toFixed(digits)))

// ------------------------------------------------------------------ colours

/** `#rrggbb` or `rgb(r g b / a)` → [r, g, b, a] with r, g, b in 0–255. */
function parseColor(value) {
  const hex = /^#([0-9a-f]{6})$/i.exec(value)
  if (hex) {
    const n = parseInt(hex[1], 16)
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1]
  }
  const rgb = /^rgb\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:\/\s*([\d.]+))?\s*\)$/.exec(value)
  if (rgb) return [Number(rgb[1]), Number(rgb[2]), Number(rgb[3]), rgb[4] === undefined ? 1 : Number(rgb[4])]
  throw new Error(`Unsupported colour "${value}": use #rrggbb or rgb(r g b / a).`)
}

// ------------------------------------------------------------------ Swift

const header = '// Generated by design/build.mjs from design/tokens.json. Do not edit.\n'

const swiftColor = (value) => {
  const [r, g, b, a] = parseColor(value)
  const c = (v) => (v / 255).toFixed(4)
  return `SwiftUI.Color(.sRGB, red: ${c(r)}, green: ${c(g)}, blue: ${c(b)}, opacity: ${num(a)})`
}
const swiftWeight = { 300: '.light', 400: '.regular', 500: '.medium', 600: '.semibold', 700: '.bold' }
const stack = (value) => (Array.isArray(value) ? value : [value])

// Helpers the generated enums use: a colour that follows the interface style,
// a themed number, and a step of the type scale.
const swiftPrelude = `/// A colour that follows the interface style, like the web's [data-theme] switch.
extension SwiftUI.Color {
    init(light: SwiftUI.Color, dark: SwiftUI.Color) {
        self.init(uiColor: UIColor { traits in
            traits.userInterfaceStyle == .dark ? UIColor(dark) : UIColor(light)
        })
    }
}

/// A value that differs between the light and the dark theme.
struct Themed<Value> {
    let light: Value
    let dark: Value
    func callAsFunction(_ scheme: ColorScheme) -> Value { scheme == .dark ? dark : light }
}

/// One step of the type scale. Tracking is in points, line height the full line.
struct TextStyle {
    let size: CGFloat
    let lineHeight: CGFloat
    let tracking: CGFloat
    let weight: SwiftUI.Font.Weight
}

/// A cubic Bézier timing curve (x1, y1, x2, y2), as CSS cubic-bezier().
struct TimingCurve {
    let x1: Double, y1: Double, x2: Double, y2: Double
}
`

/** One Swift line per token, or null for tokens that have no native form. */
function swiftLine(token) {
  const name = camel(token.path.slice(1))
  const both = (render) =>
    isThemed(token.$value)
      ? { light: render(token.$value.light), dark: render(token.$value.dark) }
      : null
  switch (token.$type) {
    case 'color': {
      const t = both(swiftColor)
      return t
        ? `static let ${name} = SwiftUI.Color(light: ${t.light}, dark: ${t.dark})`
        : `static let ${name} = ${swiftColor(token.$value)}`
    }
    // Shadows are CSS strings; a native port reads their intent from DESIGN.md.
    case 'shadow':
      return null
    case 'fontFamily':
      return `static let ${name} = "${stack(token.$value)[0]}"`
    case 'fontWeight':
      return `static let ${name}: SwiftUI.Font.Weight = ${swiftWeight[token.$value]}`
    case 'typography': {
      const v = token.$value
      return (
        `static let ${name} = TextStyle(size: ${num(v.fontSize)}, lineHeight: ${num(v.lineHeight)}, ` +
        `tracking: ${num(v.letterSpacing * v.fontSize)}, weight: ${swiftWeight[v.fontWeight ?? 400]})`
      )
    }
    case 'duration':
      return `static let ${name}: TimeInterval = ${num(token.$value / 1000)}`
    case 'cubicBezier': {
      const [x1, y1, x2, y2] = token.$value.map(num)
      return `static let ${name} = TimingCurve(x1: ${x1}, y1: ${y1}, x2: ${x2}, y2: ${y2})`
    }
    default: {
      const t = both(num)
      return t
        ? `static let ${name} = Themed<CGFloat>(light: ${t.light}, dark: ${t.dark})`
        : `static let ${name}: CGFloat = ${num(token.$value)}`
    }
  }
}

StyleDictionary.registerFormat({
  name: 'swiftui/tokens',
  format: ({ dictionary }) => {
    const groups = new Map()
    for (const token of dictionary.allTokens) {
      const line = swiftLine(token)
      if (!line) continue
      const group = token.path[0]
      if (!groups.has(group)) groups.set(group, [])
      groups.get(group).push(`        ${line}`)
    }
    const enumName = (g) => g[0].toUpperCase() + g.slice(1)
    const body = [...groups]
      .map(([g, lines]) => `    enum ${enumName(g)} {\n${lines.join('\n')}\n    }`)
      .join('\n\n')
    return `${header}\nimport SwiftUI\nimport UIKit\n\n${swiftPrelude}\nenum Tokens {\n${body}\n}\n`
  },
})

// ------------------------------------------------------------------ CSS

// Tailwind v4 theme: token groups map onto Tailwind's namespaces, so `bg-surface`,
// `px-md`, `rounded-pill`, `text-caption` (with its line height, tracking and
// weight), `shadow-float`, `backdrop-blur-glass`, `ease-sheet` just work. Durations,
// sizes, strokes and opacities have no Tailwind namespace and stay plain variables.
//
// Themes: the light values are the defaults (Tailwind puts @theme on :root). The
// dark values override the same variables under [data-theme='dark'], and under
// prefers-color-scheme: dark while no theme is chosen (no data-theme at all).
// Tailwind's utilities read the variables, so one class works in both themes.
const themeNamespace = {
  color: 'color',
  shadow: 'shadow',
  blur: 'blur',
  space: 'spacing',
  radius: 'radius',
  fontFamily: 'font',
  fontWeight: 'font-weight',
  text: 'text',
  easing: 'ease',
}
// Tailwind's own defaults in these namespaces are switched off, so only tokens
// exist: `bg-red-500` or `rounded-xl` from the default theme cannot creep in.
const resetNamespaces = ['color', 'shadow', 'blur', 'radius', 'font', 'font-weight', 'text', 'ease', 'tracking', 'leading', 'inset-shadow', 'drop-shadow']

const cssFontStack = (value) => stack(value).map((f, i) => (i === 0 ? `'${f}'` : f)).join(', ')
const rem = (px) => `${num(px / 16, 5)}rem`

/** The CSS declarations of one token in one theme: [name, value] pairs. */
function cssDeclarations(token, theme) {
  const [group, ...rest] = token.path
  const name = kebab(rest.join('-'))
  const value = valueIn(token, theme)
  const ns = themeNamespace[group]
  switch (group) {
    case 'color':
      return [[`--${ns}-${name}`, value]]
    // Tailwind copies a shadow's value into the utility instead of reading the
    // variable, so a theme could not switch it. The utility gets a reference
    // instead (themeReference), and this plain variable holds the value.
    case 'shadow':
      return [[`--elevation-${name}`, value]]
    case 'fontFamily':
      return [[`--font-${name}`, cssFontStack(value)]]
    case 'fontWeight':
      return [[`--font-weight-${name}`, String(value)]]
    // Type in rem so it follows the browser's font-size setting; the rest in px.
    case 'text': {
      const lines = [
        [`--text-${name}`, rem(value.fontSize)],
        [`--text-${name}--line-height`, rem(value.lineHeight)],
        [`--text-${name}--letter-spacing`, `${num(value.letterSpacing)}em`],
      ]
      if (value.fontWeight) lines.push([`--text-${name}--font-weight`, String(value.fontWeight)])
      return lines
    }
    case 'easing':
      return [[`--ease-${name}`, `cubic-bezier(${value.map(num).join(', ')})`]]
    case 'duration':
      return [[`--duration-${name}`, `${value}ms`]]
    case 'opacity':
      return [[`--opacity-${name}`, num(value)]]
    // Sizes and strokes are read back as a length (`size-(--size-touch)`,
    // `border-(length:--stroke-hairline)`).
    default:
      return [[ns ? `--${ns}-${name}` : `--${kebab(group)}-${name}`, `${num(value)}px`]]
  }
}

/** For shadows: the @theme entry that points the utility at the switchable variable. */
const themeReference = (token) =>
  token.path[0] === 'shadow' ? `  --shadow-${kebab(token.path.slice(1).join('-'))}: var(--elevation-${kebab(token.path.slice(1).join('-'))});` : null

StyleDictionary.registerFormat({
  name: 'css/tailwind-theme',
  format: ({ dictionary }) => {
    const theme = resetNamespaces.map((ns) => `  --${ns}-*: initial;`)
    const root = ['  color-scheme: light;']
    const dark = ['  color-scheme: dark;']
    const line = ([name, value]) => `  ${name}: ${value};`
    for (const token of dictionary.allTokens) {
      const reference = themeReference(token)
      if (reference) theme.push(reference)
      const inTheme = token.path[0] in themeNamespace && !reference
      for (const declaration of cssDeclarations(token, 'light')) (inTheme ? theme : root).push(line(declaration))
      if (isThemed(token.$value)) dark.push(...cssDeclarations(token, 'dark').map(line))
    }
    const darkBody = dark.join('\n')
    const indented = dark.map((l) => `  ${l}`).join('\n')
    return [
      '/* Generated by design/build.mjs from design/tokens.json. Do not edit. */',
      '',
      '/* Light is the default theme. `static`: every variable is emitted, also those',
      '   only scoped component styles read, not just the ones a utility uses. */',
      `@theme static {\n${theme.join('\n')}\n}`,
      '',
      `:root {\n${root.join('\n')}\n}`,
      '',
      '/* Dark, chosen in the avatar menu. */',
      `[data-theme='dark'] {\n${darkBody}\n}`,
      '',
      '/* Dark, from the device, while no theme has been chosen. */',
      `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme]) {\n${indented}\n  }\n}`,
      '',
    ].join('\n')
  },
})

// ------------------------------------------------------------------ build

// Where the generated files live in the repo. There is no native app yet, so the
// Swift file waits in design/generated/ until one points its build at it.
const outputs = {
  ios: { dir: 'generated/', file: 'Tokens.generated.swift', format: 'swiftui/tokens', transforms: ['name/camel'] },
  web: { dir: '../web/app/assets/css/', file: 'tokens.generated.css', format: 'css/tailwind-theme', transforms: ['name/kebab'] },
}

const here = (path) => fileURLToPath(new URL(path, import.meta.url))
const check = process.argv.includes('--check')
// A check builds into a scratch directory and compares, so it never touches the
// working tree and works the same locally and in CI.
const scratch = check ? mkdtempSync(join(tmpdir(), 'libellus-tokens-')) : null

// Every token needs a value for both themes or for neither: a half-themed token
// would silently keep its light value in the dark.
const tokens = JSON.parse(readFileSync(here('tokens.json'), 'utf8'))
;(function validate(node, path) {
  if (node && typeof node === 'object' && '$value' in node) {
    const v = node.$value
    if (v && typeof v === 'object' && !Array.isArray(v) && ('light' in v || 'dark' in v) && !isThemed(v)) {
      throw new Error(`${path.join('.')} has a value for only one theme.`)
    }
    return
  }
  for (const [key, child] of Object.entries(node ?? {})) {
    if (!key.startsWith('$') && typeof child === 'object') validate(child, [...path, key])
  }
})(tokens, [])

const sd = new StyleDictionary({
  tokens,
  usesDtcg: true,
  log: { verbosity: check ? 'silent' : 'default' },
  platforms: Object.fromEntries(
    Object.entries(outputs).map(([platform, o]) => [
      platform,
      {
        transforms: o.transforms,
        buildPath: check ? `${scratch}/${platform}/` : `${here(o.dir)}/`,
        files: [{ destination: o.file, format: o.format }],
      },
    ]),
  ),
})

await sd.buildAllPlatforms()

if (check) {
  const stale = Object.entries(outputs).filter(([platform, o]) => {
    const fresh = readFileSync(join(scratch, platform, o.file), 'utf8')
    let committed = ''
    try {
      committed = readFileSync(here(o.dir + o.file), 'utf8')
    } catch {}
    return fresh !== committed
  })
  rmSync(scratch, { recursive: true, force: true })
  if (stale.length) {
    for (const [, o] of stale) {
      console.error(`✗ ${relative(here('..'), here(o.dir + o.file))} does not match tokens.json`)
    }
    console.error('Generated token files are never edited by hand. Run `pnpm tokens` in design/ and commit the result.')
    process.exit(1)
  }
  console.log('✓ generated token files match tokens.json')
}
